apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-duckdns-update-script-configmap
data:
  run.sh: |
    IP=$(curl -s https://api.ipify.org)

    URL="https://www.duckdns.org/update?domains=${DOMAIN}&token=${TOKEN}&ip=${IP}"
    RESULT=$(curl -s "$URL")

    echo "DuckDNS update result: $RESULT"
