apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-duckdns-update-script-configmap
data:
  run.sh: |
    #!/usr/bin/env sh
    set -euo pipefail

    : "${DOMAIN:?DOMAIN env var is required}"
    : "${TOKEN:?TOKEN env var is required}"

    URL="https://www.duckdns.org/update?domains=${DOMAIN}&token=${TOKEN}&ip="

    RESULT="$(curl -fsS "$URL")" || RESULT="curl-error"

    echo "$(date -Is) DuckDNS update result: ${RESULT}"

    # Optional: basic success check (DuckDNS returns 'OK' on success)
    if [ "$RESULT" != "OK" ]; then
      echo "$(date -Is) ERROR: DuckDNS did not return OK" >&2
      exit 1
    fi
