apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-cron-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: DuckDNS
        metadataPolicy: None
        property: DUCKDNS_TOKEN
      secretKey: DUCKDNS_TOKEN
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        DOMAIN: "sokh"
        TOKEN: "{{ .DUCKDNS_TOKEN }}"
