global:
    postgresql:
        auth:
            username: ENC[AES256_GCM,data:NIT+NEG9,iv:Sl0vMoIXlO2tAmXTMRJL6y2KDrjbljrEjJGjLhHkHw4=,tag:N4JSMfnDqEbYp10e211Elg==,type:str]
            postgresPassword: ENC[AES256_GCM,data:7bXzCBwE3yVnSFp5ceDBMcb6gtEhtc0ezbTLnvo=,iv:OY1AqnIlDouTkcg8wFkfV6LNmefzVHZ+MAoEMgswPeA=,tag:EOA01qa1/BJZx5HoAyXxVA==,type:str]
            password: ENC[AES256_GCM,data:acsb2RMO7OU3tS7zRp2pGOtPfSwqBl4d4GpQF8IdaIbabGkqwBz2Gg==,iv:KX5yoWY2zJOyn56UPnWWFgkeOL7fbPfTRoDSSgp0og8=,tag:cp2+h3t7NkRhu+ebrcqGjg==,type:str]
            database: ENC[AES256_GCM,data:MmEk,iv:Uh190mbfoRMeaylO8s8nshQV3NI72l/TLVwlCWf7Glo=,tag:r2EvYeksKflwLIJnzM+Tng==,type:str]
sops:
    age:
        - recipient: age1erz7kqpx64wq8wjdghzz6alaurqkpsdde9zrham22zd9jlyrncpsjs3gf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTkE5M1d0ZFhud0dCbDkv
            c1NsY0M1Zk96bmxjUSt1ZDdPWXFhOFhaa0JVCmVUSHVJN044dVg3b2dtalBWeDhv
            aEFoZDhLSTJ2RExoY29DeFpmMzFPUWcKLS0tIHFYODNFcDUxNlZhRzFWbUFVdGNr
            L3c4VEhCeGdOL2U3Vno2U25BUGhuVmcK8z2JYyCle4dMRg4tFP/cysbSuDfXr0Uq
            kbySYbA1N4GIrNczRrxV1yvXVp5H1hsRgY+dl1pZGQptS/DvcePbgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T12:35:44Z"
    mac: ENC[AES256_GCM,data:DdBukIUsvo/xvYdvjdiHYl82oZHitobnoQJ6lIgcGZ+dzY9a6Y3DxnfSZyUo7fwqMk7wXp4nZUTzOnoLk+AvWRtaGdDoVpTKqpLLu+b67FyfdNXDv2IBlYVDSbKejuei0ljrRswRdaRZxovyGCeJqoHGV1z8sjh/KUvQ9FZNesQ=,iv:JSb58qq987a+EmdOKMgu477HTd2LkdsY6MuJRdOeoZM=,tag:YY+XUWm6QyTJFqaVUu/x5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
