apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: networking
  version: 1.18.0
  repo: https://kubernetes-sigs.github.io/external-dns
  includeCRDs: true
  valuesInline:
    provider:
      name: aws
    policy: upsert-only
    txtOwnerId: "homelab"
    registry: noop
    extraArgs:
      aws-zone-type: public
      domain-filter: sass.sh
      ingress-class: nginx-internal
    env:
      - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
        value: http://127.0.0.1:9911
    extraVolumeMounts:
      - name: aws-cert
        mountPath: /cert
      - name: aws-credentials
        mountPath: /shared

    extraVolumes:
      - name: aws-credentials
        emptyDir: {}
      - name: aws-cert
        secret:
          secretName: external-dns-iamra-cert

    extraContainers:
      - name: aws-signing-helper
        image: public.ecr.aws/rolesanywhere/credential-helper
        args:
          - "serve"
          - "--certificate"
          - "/cert/tls.crt"
          - "--private-key"
          - "/cert/tls.key"
          - "--trust-anchor-arn"
          - "arn:aws:rolesanywhere:ap-southeast-2:764395739071:trust-anchor/1180e313-3e11-4cf3-9b7b-44cdcda8e251"
          - "--profile-arn"
          - "arn:aws:rolesanywhere:ap-southeast-2:764395739071:profile/2187d12c-919e-470b-be38-16aeb2157319"
          - "--role-arn"
          - "arn:aws:iam::764395739071:role/external-dns-iamra-role"
        volumeMounts:
          - name: aws-cert
            mountPath: /cert
          - name: aws-credentials
            mountPath: /shared

resources:
  - resources/aws-creds.yaml
  - resources/iamra-cert.yaml
