apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: networking
  version: 1.19.0
  repo: https://kubernetes-sigs.github.io/external-dns
  includeCRDs: true
  valuesFile: values.yaml

resources:
  - resources/iamra-cert.yaml
