apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: networking
  version: 1.18.0
  repo: https://kubernetes-sigs.github.io/external-dns
  includeCRDs: true
  valuesInline:
    provider:
      name: aws
    policy: upsert-only
    txtOwnerId: "homelab"
    registry: noop
    extraArgs:
      aws-zone-type: public
      domain-filter: sass.sh
      ingress-class: nginx-internal
    env:
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /.aws/credentials
    extraVolumeMounts:
      - name: aws-credentials
        mountPath: /.aws
        readOnly: true

    extraVolumes:
      - name: aws-credentials
        secret:
          secretName: external-dns-aws-creds
resources:
  - resources/aws-creds.yaml
