provider:
  name: aws

policy: sync
txtOwnerId: "homelab"
txtPrefix: "cname-"
registry: txt

domainFilters:
  - sass.sh
  - agd.org.au

managedRecordTypes: [ "CNAME" ]

extraArgs:
  aws-zone-type: public
  ingress-class: nginx

env:
  - name: AWS_EC2_METADATA_SERVICE_ENDPOINT
    value: http://127.0.0.1:9911
  - name: AWS_REGION
    value: ap-southeast-2

extraVolumeMounts:
  - name: aws-cert
    mountPath: /cert
  - name: aws-credentials
    mountPath: /shared

extraVolumes:
  - name: aws-credentials
    emptyDir: {}
  - name: aws-cert
    secret:
      secretName: external-dns-iamra-cert

extraContainers:
  - name: aws-signing-helper
    image: public.ecr.aws/rolesanywhere/credential-helper
    args:
      - "serve"
      - "--certificate"
      - "/cert/tls.crt"
      - "--private-key"
      - "/cert/tls.key"
      - "--trust-anchor-arn"
      - "arn:aws:rolesanywhere:ap-southeast-2:764395739071:trust-anchor/1180e313-3e11-4cf3-9b7b-44cdcda8e251"
      - "--profile-arn"
      - "arn:aws:rolesanywhere:ap-southeast-2:764395739071:profile/2187d12c-919e-470b-be38-16aeb2157319"
      - "--role-arn"
      - "arn:aws:iam::764395739071:role/external-dns-iamra-role"
    volumeMounts:
      - name: aws-cert
        mountPath: /cert
      - name: aws-credentials
        mountPath: /shared
