apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-postgres-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: AGD NocoDB PostgresQL connection string
        metadataPolicy: None
        property: NC_DB
      secretKey: NC_DB
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        NC_DB: "{{ .NC_DB }}"

