apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: homelab-root-ca
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: letsencrypt.extradite316@simplelogin.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-cert
    solvers:
      - selector:
          dnsZones:
            - "agd.org.au"
        dns01:
          route53:
            region: ap-southeast-2
      - http01:
          ingress:
            ingressClassName: nginx
            ingressTemplate:
              metadata:
                annotations:
                  external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
