apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-dns-solver-aws-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cert-manager-dns-solver-aws-creds
        metadataPolicy: None
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cert-manager-dns-solver-aws-creds
        metadataPolicy: None
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
