[ req ]
default_bits        = 4096
default_md          = sha256
default_keyfile     = ca.key
distinguished_name  = req_distinguished_name
x509_extensions     = v3_ca
prompt              = no

[ req_distinguished_name ]
C  = AU
ST = Victoria
L  = Melbourne
O  = MyHomelab
CN = MyHomelab Root CA

[ v3_ca ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
basicConstraints = critical,CA:TRUE
keyUsage = critical, keyCertSign, cRLSign
