apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Sonarr
        metadataPolicy: None
        property: SONARR_API_KEY
      secretKey: SONARR_API_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Radarr
        metadataPolicy: None
        property: RADARR_API_KEY
      secretKey: RADARR_API_KEY
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        secrets.yml: |
          SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
          RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
