apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/recurring-job.yaml

helmCharts:
- name: longhorn
  releaseName: longhorn
  namespace: longhorn-system
  version: 1.10.0
  repo: https://charts.longhorn.io
  valuesInline:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: ca-issuer
      host: longhorn.home
      tls: true
      defaultSettings:
        backupTarget: "nfs://192.168.20.21:/mnt/user/longhorn-backup"
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
