apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: longhorn
  releaseName: longhorn
  namespace: longhorn-system
  version: 1.9.1
  repo: https://charts.longhorn.io
  valuesInline:
    ingress:
      ## Set to true to enable ingress record generation
      enabled: true
      host: longhorn.home
      defaultSettings:
        backupTarget: "nfs://192.168.20.21:/mnt/user/longhorn-backup"
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
