apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080 # TODO enable TLS
      vaults:
        homelab: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepass-homelab-connect-token
            key: token
