---
controllers:
  main:
    strategy: RollingUpdate
    containers:
      "{{ .Release.Name }}":
        image:
          repository: ghcr.io/skhtor/foosball-elo-frontend
          tag: latest
          pullPolicy: Always
        resources:
          requests:
            memory: 32Mi
            cpu: 50m
          limits:
            memory: 64Mi
            cpu: 100m

service:
  main:
    controller: main
    ports:
      http:
        port: 80

route:
  main:
    enabled: true
    parentRefs:
      - name: internal
        namespace: networking
        sectionName: https
    hostnames:
      - foosball.home
    additionalRules:
      - backendRefs:
          - name: foosball-elo-api
            port: 8080
        matches:
          - path:
              type: PathPrefix
              value: /api
