apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nocodb
  releaseName: nocodb
  namespace: agd
  version: 1.1.0
  repo: https://zekker6.github.io/helm-charts
  valuesInline:
    ingress:
      main:
        enabled: true
    persistence:
      data:
        enabled: false
        size: 10Gi
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          size: 10Gi
