ingress:
  main:
    enabled: true
    hosts:
      - host: nocodb.home
        paths:
          - path: /
persistence:
  data:
    enabled: true
    size: 10Gi
postgresql:
  enabled: false
  primary:
    persistence:
      enabled: true
      size: 10Gi
