ingress:
  main:
    enabled: true
    className: nginx
    hosts:
      - host: nocodb.agd.sass.sh
        paths:
          - path: /
persistence:
  data:
    enabled: true
    size: 10Gi
postgresql:
  enabled: false
  primary:
    persistence:
      enabled: true
      size: 10Gi
