ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: nocodb.agd.org.au
        paths:
          - path: /
    tls:
      - secretName: nocodb-tls
        hosts:
          - nocodb.agd.org.au
env:
  NC_DB:
    valueFrom:
      secretKeyRef:
        name: nocodb-postgres-creds
        key: NC_DB
persistence:
  data:
    enabled: true
    size: 10Gi
