env:
    NC_DB: ENC[AES256_GCM,data:u+pGhaO8xhsHWNLwE+213LYtcoba0Mmmzaqis0ufHyXUmV/hDcQmiGSbVNoh1QhiZbokBlBLunwGBttA2BrKJEgL7yr14JLl,iv:rXI3TkrOeT6euq9Of5dNTT2CuhhygaXo6ta3238Zays=,tag:k6qXzSt9ezD8imgAENd0gg==,type:str]
sops:
    age:
        - recipient: age1erz7kqpx64wq8wjdghzz6alaurqkpsdde9zrham22zd9jlyrncpsjs3gf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcC9abGdqTnNCV1ZXWmxE
            eU0wbmlMYnI4aFkrK29iVE1Xd09yWHVJZFdnCkJvOC9CR0U5YjI1VkFVeEQveTI5
            V2p3U0VCM2F0ZnhkY2s3RkpLQkQwbWcKLS0tIFk1Y012bXBrQzFMajFzYm5DSllJ
            Q1hORzZJbmdQNWxHNW0yUjBvVHc5RlEKTZ57Dj4trmUxBnehsQQW90TKvWM1JHm1
            EUPur7JDLadGedTw19JdRIN2dT5ybKxsq4DfXNrYYCpYYg+F6L1fMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T06:49:55Z"
    mac: ENC[AES256_GCM,data:N5O2OkdW44ZCEdp03zOhUaogvPXl06zCP+cMMlzoWdBD/q9eLj8HPE6DhLQJ+csMVH3SqcjE/fB0gV/SfuC2gVGTWbmyhIuGNycHCQ0G2DZOWWy2GANbPqfMUsZDobQZFgkgwb5dvFy4B0DGZNwkvf/Wy57NGmEbUORN/JuUb+I=,iv:QLMvenCRfNlzcvOWeFuc3yDiWaZoaDuLpRlx6YFsKNI=,tag:gLriyAN+l/Xxn5Ok43SE+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
