ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: nocodb.agd.sass.sh
        paths:
          - path: /
    tls:
      - secretName: nocodb-tls
        hosts:
          - nocodb.agd.sass.sh
persistence:
  data:
    enabled: true
    size: 10Gi
postgresql:
  enabled: false
  primary:
    persistence:
      enabled: true
      size: 10Gi
