---
ingress:
  enabled: false

route:
  main:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
    hostnames:
      - requests.sass.sh
    parentRefs:
      - name: public
        namespace: networking
        sectionName: https

config:
  persistence:
    size: 500Mi
    storageClass: longhorn
