apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns-internal
  namespace: networking
  version: 1.19.0
  repo: https://kubernetes-sigs.github.io/external-dns
  valuesInline:
    provider:
      name: pihole
    policy: upsert-only
    txtOwnerId: "homelab"
    registry: noop
    extraArgs:
      pihole-api-version: 6
      pihole-server: http://pihole-web
      ingress-class: nginx-internal
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
