apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  releaseName: external-dns-internal
  namespace: networking
  version: 1.18.0
  repo: https://kubernetes-sigs.github.io/external-dns
  valuesInline:
    provider: pihole
    policy: upsert-only
    txtOwnerId: "homelab"
    pihole:
      server: http://pihole-web
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
    ingressClassFilters:
      - nginx-internal
