apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx-internal
  namespace: networking
  version: 4.13.3
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      ingressClassResource:
        name: nginx-internal
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx-internal"
        parameters: {}
