apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: pihole
  releaseName: pihole
  namespace: networking
  version: 2.34.0
  repo: https://mojo2600.github.io/pihole-kubernetes/
  valuesFile: values.yaml
