DNS1:
  192.168.20.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - pihole.home
  path: /
  tls:
    - secretName: pihole-tls
      hosts:
        - pihole.home
serviceWeb:
  loadBalancerIP: 192.168.20.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.20.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
