apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: security
  version: 0.20.4
  repo: https://charts.external-secrets.io

resources:
  - ./resources/secretstore.yaml
