apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aichallenge-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        key: AI Challenge Admin Secret
        property: ADMIN_SECRET
      secretKey: ADMIN_SECRET
  target:
    creationPolicy: Owner
