apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 15 * * *"  # 2AM Daily
  task: backup
  retain: 7
  concurrency: 2
  labels:
    recurring-job-group.longhorn.io/default: enabled
