ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
    cert-manager.io/cluster-issuer: letsencrypt
  className: "nginx"
  hosts:
    - host: n8n.agd.org.au
      paths:
        - /
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.agd.org.au
main:
  persistence:
    enabled: true
    size: 5Gi
    labels:
      recurring-job-group.longhorn.io/default: enabled
  extraEnv:
    GENERIC_TIMEZONE:
      value: Australia/Melbourne
