ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
    cert-manager.io/cluster-issuer: letsencrypt
  className: "nginx"
  hosts:
    - host: n8n.agd.org.au
      paths:
        - /
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.agd.org.au
main:
  config:
    db:
      type: postgresdb
      postgresdb:
        host: postgresql
  extraEnv:
    N8N_DB_POSTGRESDB_NAME:
      value: primary
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: postgres-password
    GENERIC_TIMEZONE:
      value: Australia/Melbourne
