ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  className: nginx-internal
  hosts:
    - host: n8n.agd.home
      paths:
        - /
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.agd.home
main:
  persistence:
    enabled: true
    type: dynamic
    size: 5Gi
  extraEnv:
    GENERIC_TIMEZONE:
      value: Australia/Sydney
    WEBHOOK_URL:
      value: https://n8n.agd.org.au/

extraManifests:
  - |
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: sokh.duckdns.org
      name: n8n-public
    spec:
      ingressClassName: nginx
      rules:
        - host: n8n.agd.org.au
          http:
            paths:
              - backend:
                  service:
                    name: n8n
                    port:
                      number: 80
                path: /webhook
                pathType: Prefix
              - backend:
                  service:
                    name: n8n
                    port:
                      number: 80
                path: /rest/oauth2-credential/callback
                pathType: Exact
      tls:
        - hosts:
            - n8n.agd.org.au
          secretName: n8n-tls
