apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-aws-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Homelab External DNS AWS Credentials
        metadataPolicy: None
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Homelab External DNS AWS Credentials
        metadataPolicy: None
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        secrets.yml: |
          AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
