apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foosball-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: Personal NocoDB PostgresQL connection string
        metadataPolicy: None
        property: DATABASE_URL
      secretKey: DATABASE_URL
  target:
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        DATABASE_URL: "{{ .DATABASE_URL }}"
