---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.2.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: RollingUpdate
    containers:
      sonarr:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
          pullPolicy: Always #IfNotPresent
        env:
          PUID: "1000"
          PGID: "100"
          TZ: Australia/Melbourne

service:
  main:
    controller: main

ingress:
  main:
    hosts:
      - host: sonarr.home
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http

persistence:
  sonarr-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config
  nfs-media:
    existingClaim: media-server-nfs-pvc
    globalMounts:
      - path: /media
