---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.2.0/charts/other/app-template/values.schema.json

controllers:
  main:
    strategy: RollingUpdate
    containers:
      sonarr:
        image:
          repository: lscr.io/linuxserver/sonarr
          tag: latest
          pullPolicy: Always #IfNotPresent
        env:
          PUID: "1000"
          PGID: "100"
          TZ: Australia/Melbourne

service:
  sonarr:
    controller: main
    ports:
      http:
        port: 80
        targetPort: 8989

ingress:
  sonarr:
    hosts:
      - host: sonarr.home
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: sonarr
              port: http

persistence:
  data-pvc:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /config
