---
controllers:
  main:
    strategy: RollingUpdate
    defaultContainerOptions:
      envFrom:
        - configMapRef:
            name: common-settings
    containers:
      "{{ .Release.Name }}":
        image:
          repository: lscr.io/linuxserver/radarr
          tag: latest
          pullPolicy: Always

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

route:
  main:
    enabled: true
    parentRefs:
      - name: internal
        namespace: networking
        sectionName: https
    hostnames:
      - radarr.sass.home

persistence:
  radarr-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config
  nfs-media:
    existingClaim: media-server-nfs-pvc
    globalMounts:
      - path: /media
