apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metrics-server
  releaseName: metrics-server
  namespace: monitoring
  version: 3.13.0
  repo: https://kubernetes-sigs.github.io/metrics-server/
