---
controllers:
  main:
    strategy: RollingUpdate
    defaultContainerOptions:
      envFrom:
        - configMapRef:
            name: common-settings
    containers:
      "{{ .Release.Name }}":
        image:
          repository: lscr.io/linuxserver/sabnzbd
          tag: latest
          pullPolicy: Always

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - host: sabnzbd.home
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: sabnzbd-tls
        hosts:
          - sabnzbd.home

persistence:
  sabnzbd-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    globalMounts:
      - path: /config
  nfs-media:
    existingClaim: media-server-nfs-pvc
    globalMounts:
      - path: /media/downloads/usenet
        subPath: downloads/usenet
