auth:
    database: ENC[AES256_GCM,data:/EjMGg==,iv:8nsuyodU/PeRNLgVim6Z2BnGtFQVdPE8szHSaxctqXQ=,tag:eQ+eFr5krdoHOsEEAIAdrw==,type:str]
    username: ENC[AES256_GCM,data:EZdGJQ==,iv:F2Kb+tQ2k+eXLu49H0K9R7IopXvTA5ps0QUzVixEON4=,tag:vkWNLcSd1kypK8j7tiyXcQ==,type:str]
    password: ENC[AES256_GCM,data:Pu9BKsvOBrqBdC7BjbTmbQ==,iv:3rRMQEzC7N0xch4C7uFsx8a2jfHPvi73YLA891/hPzw=,tag:FlkRxOI5ZNCwX8kR457lpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSXpXSFFucTVYSmZ5L1l3
            bWNsMXlvS1FSdHJRV0o0MGdNbGh0QXl3ZHpvCnc0eWIvVlhnYzh2TitvV2JaUURa
            NnFQNWV6VGFxMkdHUTVtNzYwN0VOMmsKLS0tIGhaUGhqUTk2VUw4VjVzVUxWZCtj
            bU1Pc21lS0g1cDVCVmhLaGpxREJ5WG8KVDpxi2w/rEgZYBIUDMIgBQYRCyGqsZio
            eNQkmm4MogmlKuhQ2s0sJdP0XI3l6oQabx87o/TANoJWx7d5fUCYWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1erz7kqpx64wq8wjdghzz6alaurqkpsdde9zrham22zd9jlyrncpsjs3gf6
    lastmodified: "2026-05-18T10:22:00Z"
    mac: ENC[AES256_GCM,data:V7MH6mtmgDd4MJONKn8LAcM68JBjPCGbVHbJXK5YAQp35D46ZP8FnEIK9QGSDdiDkspTPzS01JRamSjd3xfL4nJIOfT3gvR/JOK/dndEVLRKsfstP1go1s7ucYH8tVgAtjRFBtbsdFxNgsoujkB5g15oruXieeIUPErYmcyeF+Q=,iv:c33z69aPYhuL5K+xLNF3Db9iqpc7LEHrbEmnB+5/uWA=,tag:6Sjc8pKnuq7lo7FFzxbsfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
