apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: connect
  releaseName: 1password-connect
  namespace: security
  version: 2.0.5
  repo: https://1password.github.io/connect-helm-charts
  valuesInline:
    operator:
      token:
        key: onepass-homelab-connect-token
