---
controllers:
  main:
    strategy: RollingUpdate
    defaultContainerOptions:
      envFrom:
        - configMapRef:
            name: common-settings
    containers:
      "{{ .Release.Name }}":
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: latest
          pullPolicy: Always

service:
  main:
    controller: main
    ports:
      http:
        port: 9696

route:
  main:
    enabled: true
    parentRefs:
      - name: internal
        namespace: networking
        sectionName: https
    hostnames:
      - prowlarr.home

persistence:
  prowlarr-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /config
